name: Media Server
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8585:80
    volumes:
      - /data/media/books:/audiobooks
      - /data/media/books:/podcasts
      - /configs/audiobookshelf:/config
      - /data/media/books/audiobookshelf:/metadata
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - .env
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    pull_policy: always
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /configs/jellyfin:/config
      - /data/media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    restart: always
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${JELLYFIN_IPV4_ADDR}
  jelly-music-app:
    image: ghcr.io/stannnnn/jelly-music-app:latest
    container_name: jellyfin-music
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - JELLYAPP_PORT=8100
      - DEFAULT_JELLYFIN_URL=http://${JELLYFIN_HOST_IPV4_ADDR}:8096
      - LOCK_JELLYFIN_URL=true
    ports:
      - 8100:80
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    pull_policy: always
    user: 1000:1000
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    volumes:
      - /configs/seerr:/app/config
    restart: always
    network_mode: service:gluetun
    env_file:
      - .env
    depends_on:
      gluetun:
        condition: service_healthy
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
